### ISSUE TITLE
Please clarify where to place these files

### ISSUE THREAD

**Issue by jsmm** [fletcher/peg-multimarkdown-latex-support#5]
If these files are still relevant for MMD 4, please advice where to place them. With MacTeX on Yosemite there is no folder ~/Library/texmf/tex/latex/mmd, nor  ~/texmf/tex/latex/mmd.
Thank you.

**Comment by fletcher** [comment]
You put them wherever your LaTeX installation needs them to be.  I use MacTeX, and that's where they belong.  Your install may be different, but that's a TeX support issue, not a MultiMarkdown issue.  I can't support users in trying to understand all the nuances of LaTeX -- it's too complex a piece of software.
